emoji_list = [
    ':money-mouth_face:', ':smirking_face:', ':smiling_face_with_sunglasses:', ':face_screaming_in_fear:',
    ':smiling_face_with_horns:', ':skull_and_crossbones:', ':skull:', ':imp:', ':pouting_face:', ':pile_of_poo:',
    ':clown_face:', ':robot_face:', ':pile_of_poo:', ':alien_monster:', ':ghost:', ':japanese_ogre:',
    ':hear-no-evil_monkey:', ':eyes:', ':flexed_biceps:', ':bearded_person:', ':baby:', ':older_man:',
    ':older_woman:', ':bearded_person:', ':person_frowning:', ':guardsman:', ':man_with_gua_pi_mao:',
    ':sleuth_or_spy:', ':man_with_turban:', ':police_officer:', ':prince:', ':vampire:', ':fairy:', ':genie:',
    ':mage:', ':merperson:', ':elf:', ':zombie:', ':superhero:', ':supervillain:', ':haircut:', ':dancer:',
    ':chipmunk:', ':cow_face:', ':mouse_face:', ':dromedary_camel:', ':tiger_face:', ':rhinoceros:', ':gorilla:',
    ':deer:', ':fox_face:', ':rat:', ':koala:', ':kangaroo:', ':bat:', ':horse:', ':goat:', ':ram:', ':monkey:',
    ':sheep:', ':dog:', ':pig:', ':boar:', ':cat_face:', ':hippopotamus:', ':rabbit_face:', ':raccoon:', ':poodle:',
    ':hedgehog:', ':mouse:', ':cow:', ':monkey_face:', ':leopard:', ':tiger:', ':rabbit:', ':cat:', ':unicorn_face:',
    ':elephant:', ':water_buffalo:', ':horse_face:', ':ox:', ':dog_face:', ':pig_face:', ':badger:', ':sloth:',
    ':pig_nose:', ':paw_prints:', ':panda_face:', ':lion_face:', ':hatching_chick:', ':chicken:', ':baby_chick:',
    ':dove_of_peace:', ':flamingo:', ':front-facing_baby_chick:', ':swan:', ':penguin:', ':bird:', ':rooster:',
    ':parrot:', ':peacock:', ':turkey:', ':eagle:', ':owl:', ':duck:', ':snake:', ':lizard:', ':turtle:',
    ':crocodile:', ':sauropod:', ':t-rex:', ':dragon:', ':dragon_face:', ':whale:', ':shark:', ':spiral_shell:',
    ':spouting_whale:', ':fish:', ':octopus:', ':dolphin:', ':blowfish:', ':tropical_fish:', ':butterfly:', ':cricket:',
    ':mosquito:', ':beetle:', ':scorpion:', ':honeybee:', ':lady_beetle:', ':bug:', ':ant:', ':spider_web:', ':snail:',
    ':orangutan:', ':otter:', ':llama:', ':skunk:', ':guide_dog:',
]